import type { InventoryItem } from "../../types/api";

export const SHOWCASE_INVENTORY: InventoryItem[] = [
  {
    stockNumber: "38492019",
    title: "2023 Toyota Camry LE Sedan",
    year: 2023,
    make: "Toyota",
    model: "Camry",
    vin: "4T1B11HK5PU184920",
    odometer: 28450,
    vehicleScore: 92,
    primaryDamage: "Normal Wear",
    secondaryDamage: "None",
    auctionDate: "Thu, Oct 15 • 10:30 AM CDT",
    auctionAt: Math.floor(Date.now() / 1000) + 86400 * 3,
    buyNowPrice: 24500,
    currentBid: 14200,
    startCode: "Run & Drive",
    branch: "Dallas, TX - North",
    vehicleType: "Automobile",
    fuelType: "Gasoline",
    transmission: "Automatic",
    airbags: "Intact",
    imageUrl: "/assets/featured_camry.jpg",
    titleDoc: "Clean Title",
    keyStatus: "Yes",
    bodyStyle: "Sedan",
    engine: "2.5L 4-Cylinder",
    extColor: "Midnight Black",
    intColor: "Ash Grey",
    sellerType: "Fleet / Lease",
    acv: 24500,
    drivelineType: "FWD",
  },
  {
    stockNumber: "39201847",
    title: "2022 Honda CR-V EX AWD",
    year: 2022,
    make: "Honda",
    model: "CR-V",
    vin: "2HKRW2H59NH291048",
    odometer: 34120,
    vehicleScore: 89,
    primaryDamage: "Minor Dent/Scratches",
    secondaryDamage: "None",
    auctionDate: "Fri, Oct 16 • 01:00 PM CDT",
    auctionAt: Math.floor(Date.now() / 1000) + 86400 * 4,
    buyNowPrice: 26800,
    currentBid: 16800,
    startCode: "Run & Drive",
    branch: "Fort Worth, TX",
    vehicleType: "SUV",
    fuelType: "Gasoline",
    transmission: "CVT",
    airbags: "Intact",
    imageUrl: "/assets/featured_crv.jpg",
    titleDoc: "Clean Title",
    keyStatus: "Yes",
    bodyStyle: "SUV",
    engine: "1.5L Turbo 4-Cyl",
    extColor: "Platinum White",
    intColor: "Black Leather",
    sellerType: "Insurance",
    acv: 27900,
    drivelineType: "AWD",
  },
  {
    stockNumber: "37402910",
    title: "2021 Ford F-150 XLT SuperCrew 4x4",
    year: 2021,
    make: "Ford",
    model: "F-150",
    vin: "1FTFW1E85MFA38201",
    odometer: 42800,
    vehicleScore: 88,
    primaryDamage: "Rear End",
    secondaryDamage: "Minor Dent",
    auctionDate: "Mon, Oct 19 • 11:00 AM CDT",
    auctionAt: Math.floor(Date.now() / 1000) + 86400 * 7,
    buyNowPrice: 32000,
    currentBid: 19500,
    startCode: "Run & Drive",
    branch: "Houston, TX - South",
    vehicleType: "Truck",
    fuelType: "Gasoline",
    transmission: "10-Speed Automatic",
    airbags: "Intact",
    imageUrl: "/assets/featured_f150.jpg",
    titleDoc: "Salvage Certificate",
    keyStatus: "Yes",
    bodyStyle: "Truck",
    engine: "3.5L V6 EcoBoost",
    extColor: "Oxford White",
    intColor: "Medium Dark Slate",
    sellerType: "Insurance",
    acv: 35400,
    drivelineType: "4WD",
  },
  {
    stockNumber: "40192837",
    title: "2023 Tesla Model Y Long Range AWD",
    year: 2023,
    make: "Tesla",
    model: "Model Y",
    vin: "7SAYGDEE9PF892014",
    odometer: 19200,
    vehicleScore: 94,
    primaryDamage: "Normal Wear",
    secondaryDamage: "None",
    auctionDate: "Tue, Oct 20 • 02:30 PM CDT",
    auctionAt: Math.floor(Date.now() / 1000) + 86400 * 8,
    buyNowPrice: 37900,
    currentBid: 24800,
    startCode: "Run & Drive",
    branch: "Austin, TX",
    vehicleType: "Electric",
    fuelType: "Electric",
    transmission: "Single-Speed",
    airbags: "Intact",
    imageUrl: "/assets/featured_modely.jpg",
    titleDoc: "Clean Title",
    keyStatus: "Yes",
    bodyStyle: "Electric",
    engine: "Dual Motor Electric",
    extColor: "Pearl White Multi-Coat",
    intColor: "All Black Premium",
    sellerType: "Financial Institution",
    acv: 39500,
    drivelineType: "AWD",
  },
  {
    stockNumber: "36291048",
    title: "2022 BMW 3 Series 330i xDrive Sedan",
    year: 2022,
    make: "BMW",
    model: "3 Series",
    vin: "WBA5R7C00NFK29104",
    odometer: 26300,
    vehicleScore: 91,
    primaryDamage: "Minor Front Bumper",
    secondaryDamage: "None",
    auctionDate: "Wed, Oct 21 • 09:30 AM CDT",
    auctionAt: Math.floor(Date.now() / 1000) + 86400 * 9,
    buyNowPrice: 31500,
    currentBid: 18900,
    startCode: "Run & Drive",
    branch: "San Antonio, TX",
    vehicleType: "Luxury",
    fuelType: "Gasoline",
    transmission: "8-Speed Sport Automatic",
    airbags: "Intact",
    imageUrl: "/assets/cat_luxury.jpg",
    titleDoc: "Clean Title",
    keyStatus: "Yes",
    bodyStyle: "Luxury",
    engine: "2.0L TwinPower Turbo",
    extColor: "Mineral Grey Metallic",
    intColor: "Cognac Vernasca Leather",
    sellerType: "Fleet",
    acv: 33800,
    drivelineType: "AWD",
  },
  {
    stockNumber: "38920194",
    title: "2021 Chevrolet Tahoe LT 4WD",
    year: 2021,
    make: "Chevrolet",
    model: "Tahoe",
    vin: "1GNSKCKD4MR392018",
    odometer: 48900,
    vehicleScore: 87,
    primaryDamage: "Side Scrape",
    secondaryDamage: "None",
    auctionDate: "Thu, Oct 22 • 01:30 PM CDT",
    auctionAt: Math.floor(Date.now() / 1000) + 86400 * 10,
    buyNowPrice: 42000,
    currentBid: 27500,
    startCode: "Run & Drive",
    branch: "Oklahoma City, OK",
    vehicleType: "SUV",
    fuelType: "Gasoline",
    transmission: "10-Speed Automatic",
    airbags: "Intact",
    imageUrl: "/assets/tradein_suv.jpg",
    titleDoc: "Clean Title",
    keyStatus: "Yes",
    bodyStyle: "SUV",
    engine: "5.3L EcoTec3 V8",
    extColor: "Shadow Grey Metallic",
    intColor: "Jet Black Leather",
    sellerType: "Trade-In",
    acv: 44900,
    drivelineType: "4WD",
  },
  {
    stockNumber: "41029384",
    title: "2023 BMW M4 Competition Coupe",
    year: 2023,
    make: "BMW",
    model: "M4",
    vin: "WBS33AY08PF410293",
    odometer: 14200,
    vehicleScore: 95,
    primaryDamage: "Normal Wear",
    secondaryDamage: "None",
    auctionDate: "Fri, Oct 23 • 12:00 PM CDT",
    auctionAt: Math.floor(Date.now() / 1000) + 86400 * 11,
    buyNowPrice: 68000,
    currentBid: 49000,
    startCode: "Run & Drive",
    branch: "Dallas, TX - North",
    vehicleType: "Luxury",
    fuelType: "Gasoline",
    transmission: "8-Speed M Steptronic",
    airbags: "Intact",
    imageUrl: "/assets/prefooter_bmw.jpg",
    titleDoc: "Clean Title",
    keyStatus: "Yes",
    bodyStyle: "Luxury",
    engine: "3.0L M TwinPower Turbo",
    extColor: "Isle of Man Green",
    intColor: "Kyalami Orange Full Leather",
    sellerType: "Insurance",
    acv: 76500,
    drivelineType: "RWD",
  },
  {
    stockNumber: "37829104",
    title: "2022 Toyota RAV4 XLE Premium",
    year: 2022,
    make: "Toyota",
    model: "RAV4",
    vin: "2T3P1RFV7NC378291",
    odometer: 31200,
    vehicleScore: 90,
    primaryDamage: "Minor Front",
    secondaryDamage: "None",
    auctionDate: "Mon, Oct 26 • 10:00 AM CDT",
    auctionAt: Math.floor(Date.now() / 1000) + 86400 * 14,
    buyNowPrice: 28500,
    currentBid: 17200,
    startCode: "Run & Drive",
    branch: "Arlington, TX",
    vehicleType: "SUV",
    fuelType: "Gasoline",
    transmission: "8-Speed Automatic",
    airbags: "Intact",
    imageUrl: "/assets/hero_suv.jpg",
    titleDoc: "Clean Title",
    keyStatus: "Yes",
    bodyStyle: "SUV",
    engine: "2.5L 4-Cylinder",
    extColor: "Magnetic Gray Metallic",
    intColor: "Black SofTex",
    sellerType: "Dealer Consignment",
    acv: 29800,
    drivelineType: "AWD",
  },
];
